VOWEL = 0
STOP = 1
AFFRICATE = 2
FRICATIVE = 3
ASPIRATE = 4
LIQUID = 5
NASAL = 6
SEMIVOWEL = 7

PHONEMES_LIST = {
    'AA': VOWEL,
    'AA0': VOWEL,
    'AA1': VOWEL,
    'AA2': VOWEL,
    'AE': VOWEL,
    'AE0': VOWEL,
    'AE1': VOWEL,
    'AE2': VOWEL,
    'AH': VOWEL,
    'AH0': VOWEL,
    'AH1': VOWEL,
    'AH2': VOWEL,
    'AO': VOWEL,
    'AO0': VOWEL,
    'AO1': VOWEL,
    'AO2': VOWEL,
    'AW': VOWEL,
    'AW0': VOWEL,
    'AW1': VOWEL,
    'AW2': VOWEL,
    'AY': VOWEL,
    'AY0': VOWEL,
    'AY1': VOWEL,
    'AY2': VOWEL,
    'B': STOP,
    'CH': AFFRICATE,
    'D': STOP,
    'DH': FRICATIVE,
    'EH': VOWEL,
    'EH0': VOWEL,
    'EH1': VOWEL,
    'EH2': VOWEL,
    'ER': VOWEL,
    'ER0': VOWEL,
    'ER1': VOWEL,
    'ER2': VOWEL,
    'EY': VOWEL,
    'EY0': VOWEL,
    'EY1': VOWEL,
    'EY2': VOWEL,
    'F': FRICATIVE,
    'G': STOP,
    'HH': ASPIRATE,
    'IH': VOWEL,
    'IH0': VOWEL,
    'IH1': VOWEL,
    'IH2': VOWEL,
    'IY': VOWEL,
    'IY0': VOWEL,
    'IY1': VOWEL,
    'IY2': VOWEL,
    'JH': AFFRICATE,
    'K': STOP,
    'L': LIQUID,
    'M': NASAL,
    'N': NASAL,
    'NG': NASAL,
    'OW': VOWEL,
    'OW0': VOWEL,
    'OW1': VOWEL,
    'OW2': VOWEL,
    'OY': VOWEL,
    'OY0': VOWEL,
    'OY1': VOWEL,
    'OY2': VOWEL,
    'P': STOP,
    'R': LIQUID,
    'S': FRICATIVE,
    'SH': FRICATIVE,
    'T': STOP,
    'TH': FRICATIVE,
    'UH': VOWEL,
    'UH0': VOWEL,
    'UH1': VOWEL,
    'UH2': VOWEL,
    'UW': VOWEL,
    'UW0': VOWEL,
    'UW1': VOWEL,
    'UW2': VOWEL,
    'V': FRICATIVE,
    'W': SEMIVOWEL,
    'Y': SEMIVOWEL,
    'Z': FRICATIVE,
    'ZH': FRICATIVE,
}

# John Algeo (1978) What Consonant Clusters Are Possible?, Word, 29:3, 206-224, DOI: 10.1080/00437956.1978.11435661
## See ReadMe for an explanation of why these onset clusters are included
TWO_ONSET_CLUSTERS = set([
    ('B', 'L'), # "Agreement on 30" section, with three-syllable onset clusters separated out
    ('B', 'R'),
    ('D', 'R'),
    ('D', 'W'),
    ('F', 'L'),
    ('F', 'R'),
    ('G', 'L'),
    ('G', 'R'),
    ('K', 'L'),
    ('K', 'R'),
    ('K', 'W'),
    ('P', 'L'),
    ('P', 'R'),
    ('S', 'K'),
    ('S', 'L'),
    ('S', 'N'),
    ('S', 'P'),
    ('S', 'T'),
    ('S', 'W'),
    ('SH', 'R'),
    ('T', 'R'),
    ('T', 'W'),
    ('TH', 'R'),
    ('TH', 'W'),
    ('B', 'Y'), # "Discrepencies of Method" section
    ('F', 'Y'),
    ('HH', 'Y'),
    ('K', 'Y'),
    ('M', 'Y'),
    ('P', 'Y'),
    ('V', 'Y'),
    ('G', 'W'), # "Discrepencies of Word Class" (didn't include most from this section but had to include this because CMU dictionary often does NG G W as in 'extinguish')
    ('F', 'W'),
    ('F', 'Y'),
    ('G', 'Y'),
    ('V', 'R'),
])

THREE_ONSET_CLUSTERS = set([ # From Pearce
    ('S', 'P', 'L'), # I feel like the S may be part of the prior syllable as well sometimes, hmm...
    ('S', 'P', 'R'),
    ('S', 'P', 'Y'),
    ('S', 'T', 'R'),
    ('S', 'T', 'Y'),
    ('S', 'K', 'L'),
    ('S', 'K', 'R'),
    ('S', 'K', 'W'),
    ('S', 'K', 'Y')
])